baseurl: 'http://localhost:1818/'
url: ''
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - /gulp
  - /node_modules
  - gulpfile.js
  - _assets
  - bower.json
  - Gemfile
  - Gemfile.lock
  - package.json
  - .publish
site-structure: multipage
g-analytics: UA-59944728-3
fb-app-id: '915671155245552'
see-also:
  - 'http://work.diogorusso.com'
  - 'http://www.lucaszappa.com.br'
  - 'http://www.estudioberinjela.com.br'
paginate: 4
paginate_home: /work
paginate_link: /work/page
paginate_path: '/work/page:num'
img-path: /lib/img
img-max-width: '1920'
author: Diogo Russo
job: experience designer
title: Estúdio Berinjela | Criação
description: >-
  I'm a DESIGNER and STORYTELLER I help businesses, individuals and communities
  craft meaningful EXPERIENCES and PRODUCTS
logo: +logo.png
favico: /lib/img/_favicon.ico
avatar: +avatar.png
card: /lib/img/_site_card.jpg
email: hello@diogorusso.com
country: United States
region: California
city: Berkeley
img-bio-max-size: 791
img-bio-breakpoints:
  - 791
  - 480
img-profile: bio-img-profile.jpg
img-card: bio-img-postcard.jpg
txt-bio-bg: '#ccc'
txt-bio: >-
  Aqui designers, FILMAKERS, FOTÓGRAFOS, ILUSTRADORES, ARTISTAS e entusiastas
  trabalham de maneira colaborativa, com dedicação, para transformar IDEIAS em
  RESULTADOS.
txt-bio-2: >-
  Entre os diversos trabalhos realizados destacam-se vídeos institucionais,
  coberturas audiovisuais, identidade visual, curadoria e produção artística.
bio-btn-txt: Perfil Completo
bio-btn-link: 'https://www.linkedin.com/in/diogorusso/en'
skills:
  - title: 1 Idéia
    icon: /lib/img/bio-skill-img-01.png
  - title: 2 Proposta
    icon: /lib/img/bio-skill-img-02.png
  - title: 3 Criação
    icon: /lib/imgs/bio-skill-img-03.png
  - title: 4 Fim
    icon: /lib/img/bio-skill-img-04.png
hero-title: Estúdio Berinjela
hero-subtitle: Ajudamos pessoas e negócios a<br> melhor comunicarem suas ideias.
hero-btn-txt: mais
hero-key-word-1: Vídeos e Motion
hero-key-word-2: Pautas e Coberturas
hero-key-word-3: Design e Ilustração
hero-key-word-4: Orientação Criativa
hero-transtion: slide
hero-arrows: false
hero-autoplay: false
hero-bgs:
  - title: Hello
    src: hero-slide-bg-01.jpg
  - title: Hello 2
    src: hero-slide-bg-01.jpg
menu-links_multipage:
  - title: Work
    url: /
  - title: Ideas
    url: /work
  - title: Newsletter
    url: /sign-up.html
    icon: heart
    icon-color: fff
  - title: Connect
    url: '#connect'
menu-links_onepage:
  - title: O Estúdio
    url: '#bio'
  - title: Criação
    url: '#process-steps-bar'
  - title: Portfolio
    url: '#work'
  - title: Contato
    url: '#connect'
    icon: heart
    icon-color: f14b4b
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      auto-scroll: false
      txt-color: dark
      hero: true
      hero-bg-color: '#000'
      title: TITLE DEFAULT
      cover: /lib/content/cover/post-default-cover.jpg
      description: DESCRIPTION DEFAULT
      tags:
        - journal
section-process-url: process
process-steps:
  - title: Vídeo <br>& Motion
    id: 1
    color: 50E3C2
    link: ''
    icon: /lib/img/process-bar-img-step-1.png
    icon-bg: '000'
    img: step_0_creativity_img.jpg
    description: >-
      I use design thinking and creative problem solving methods to help
      business, individuals and communities to explore and embrace new ideas.
  - title: Pautas &<br> Coberturas
    id: 2
    color: F8E71C
    link: experience
    icon: /lib/img/process-bar-img-step-2.png
    icon-bg: '000'
    img: step_1_experience_img.jpg
    description: >-
      I conduct interviews, workshops and research projects with internal and
      external stakeholders.
  - title: Experiências <br>Web
    id: 3
    color: BD71FF
    link: document
    icon: /lib/img/process-bar-img-step-3.png
    icon-bg: '000'
    img: step_2_document_img.jpg
    description: >-
      I create detailed and delightful infographics, presentations, e-books,
      prints and illustrations
  - title: Design Gráfico <br> & Ilustração
    id: 4
    color: 4A90E2
    link: prototype
    icon: /lib/img/process-bar-img-step-4.png
    icon-bg: '000'
    img: step_3_prototype_img.jpg
    description: >-
      I create prototypes, experiments and iterations to refine ideas through
      continuous feedback loops.
  - title: Oficinas<br> & Eventos
    id: 5
    color: F5A623
    link: design
    icon: /lib/img/process-bar-img-step-5.png
    icon-bg: '000'
    img: step_4_design_img.jpg
    description: >-
      I design meaningful experiences, products and graphics for business,
      individuals and communities.
  - title: Connect<br> & Inspire
    id: 6
    color: f14b4b
    link: work
    icon: /lib/img/process-bar-img-step-6.png
    icon-bg: '000'
    img: step_4_design_img.jpg
    description: >-
      I use design thinking and creative problem solving methods to help
      business, individuals and communities to explore and embrace new ideas.
social:
  - name: behance
    url: 'https://www.behance.net/diogorusso'
  - name: linkedin
    url: 'https://www.linkedin.com/in/diogorusso/en'
  - name: envelope-o
    url: 'mailto:contato@estudioberinjela.com.br'
section-work-title: Portfolio
work-call-to-action-btns:
  - title: Experience & Product
    link: '#'
    bg-color: '#f7f7f7'
  - title: Creative Direction
    link: '#'
    bg-color: '#ecebeb'
  - title: Web & Graphics
    link: '#'
    bg-color: '#e4e4e4'
  - title: Illustration & Art
    link: '#'
    bg-color: '#dcdcdc'
  - title: All My Projects
    link: '#'
    bg-color: '#cccccc'
  - title: Tools & Methods
    link: '#'
    bg-color: '#c7c7c7'
projects-featured:
  - cover: portfolio-cover-01.jpg
    title: LaunchPad UX
    fields: 'UI/UX, Product Design'
    url: 'http://work.diogorusso.com/launchpad'
  - cover: portfolio-cover-02.jpg
    title: World Cup Brazil
    fields: 'Creative Direction, Film, Photography'
    url: >-
      http://work.diogorusso.com/fwc-2014-conteudo-multimidia-cobertura-coca-cola
  - cover: portfolio-cover-03.jpg
    title: Kenner IxD & Video
    fields: 'Creative Direction, Interaction Design'
    url: 'http://work.diogorusso.com/kenner-ixd-motion'
  - cover: portfolio-cover-04.jpg
    title: FOODTOPIA xD
    fields: 'Entrepreneurship, Product Design'
    url: 'http://work.diogorusso.com/foodtopia'
  - cover: portfolio-cover-05.jpg
    title: Wordpress for Startups
    fields: 'UI/UX, Web Design'
    url: 'http://work.diogorusso.com/webdesign-for-business'
  - cover: portfolio-cover-06.jpg
    title: SESC School ID
    fields: 'Branding, Graphic Design'
    url: 'http://work.diogorusso.com/escola-sesc-id'
